# Generated by Django 5.2 on 2025-04-29 06:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house', models.CharField(max_length=20, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(verbose_name='Дата заезда')),
                ('checkout_date', models.DateField(verbose_name='Дата выезда')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая стоимость')),
                ('status', models.CharField(choices=[('Новый', 'Новый'), ('Подтвержден', 'Подтвержден'), ('Оплачен', 'Оплачен'), ('Отменен', 'Отменен'), ('Завершен', 'Завершен')], default='Новый', max_length=50, verbose_name='Статус бронирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('passport_data', models.CharField(max_length=50, unique=True, verbose_name='Паспортные данные')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-registration_date', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость за ночь')),
            ],
            options={
                'verbose_name': 'Тип номера',
                'verbose_name_plural': 'Типы номеров',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_checkin_date', models.DateField(verbose_name='Фактическая дата заезда')),
                ('actual_checkout_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата выезда')),
                ('status', models.CharField(choices=[('Проживает', 'Проживает'), ('Выехал', 'Выехал')], default='Проживает', max_length=50, verbose_name='Статус проживания')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation', to='hotel.booking', verbose_name='Бронирование')),
            ],
            options={
                'verbose_name': 'Проживание',
                'verbose_name_plural': 'Проживания',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название гостиницы')),
                ('description', models.TextField(verbose_name='Описание здания')),
                ('capacity', models.IntegerField(verbose_name='Количество мест')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='hotel.address', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Гостиница',
                'verbose_name_plural': 'Гостиницы',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotel.client', verbose_name='Клиент'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hotel.building', verbose_name='Гостиница')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата платежа')),
                ('payment_method', models.CharField(choices=[('Наличные', 'Наличные'), ('Карта', 'Карта'), ('Онлайн', 'Онлайн')], max_length=50, verbose_name='Метод оплаты')),
                ('status', models.CharField(choices=[('Оплачен', 'Оплачен'), ('Отменен', 'Отменен'), ('Возврат', 'Возврат')], default='Оплачен', max_length=50, verbose_name='Статус платежа')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hotel.booking', verbose_name='Бронирование')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.employee', verbose_name='Сотрудник')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность сотрудника',
                'verbose_name_plural': 'Должности сотрудников',
                'unique_together': {('employee', 'position')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='positions',
            field=models.ManyToManyField(related_name='employees', through='hotel.EmployeePositions', to='hotel.position', verbose_name='Должности'),
        ),
        migrations.CreateModel(
            name='BuildingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Доступное количество')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.building', verbose_name='Гостиница')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в гостинице',
                'verbose_name_plural': 'Товары в гостинице',
                'unique_together': {('product', 'building')},
            },
        ),
        migrations.AddField(
            model_name='building',
            name='products',
            field=models.ManyToManyField(through='hotel.BuildingProducts', to='hotel.product', verbose_name='Товары'),
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата заказа')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая стоимость')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='hotel.accommodation', verbose_name='Проживание')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ товара',
                'verbose_name_plural': 'Заказы товаров',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('publication_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='hotel.booking', verbose_name='Бронирование')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotel.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Свободен', 'Свободен'), ('Занят', 'Занят'), ('На обслуживании', 'На обслуживании'), ('Требует уборки', 'Требует уборки')], default='Свободен', max_length=50, verbose_name='Статус номера')),
                ('room_number', models.CharField(max_length=20, verbose_name='Номер комнаты')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.building', verbose_name='Здание')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.roomtype', verbose_name='Тип номера')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'unique_together': {('building', 'room_number')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotel.room', verbose_name='Номер'),
        ),
        migrations.CreateModel(
            name='BuildingServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.building', verbose_name='Гостиница')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга в гостинице',
                'verbose_name_plural': 'Услуги в гостинице',
                'unique_together': {('service', 'building')},
            },
        ),
        migrations.AddField(
            model_name='building',
            name='services',
            field=models.ManyToManyField(through='hotel.BuildingServices', to='hotel.service', verbose_name='Услуги'),
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата заказа')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая стоимость')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='hotel.accommodation', verbose_name='Проживание')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Заказ услуги',
                'verbose_name_plural': 'Заказы услуг',
                'ordering': ['-order_date'],
            },
        ),
    ]
