# Generated by Django 5.2 on 2025-06-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingproducts',
            name='available',
        ),
        migrations.AddField(
            model_name='buildingproducts',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='В наличии'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
